- name: Wait for the instances to come up and check ssh
  hosts: all
  gather_facts: false
  tasks:
  - name: Wait for SSH to start
    wait_for:
      port: 22
      timeout: 120
    delegate_to: localhost

- name: Install software on u1
  hosts: aws_u1
  vars:
    packages:
      - openjdk-8-jdk
      - python3
      - mysql-client
      - python-msql.connector

  tasks:
    - name: Update all Ubuntu packages
      become: yes
      apt:
        upgrade: "dist"
      when: ansible_distribution == 'Ubuntu'

    - name: Install all packages
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "{{ packages }}"
        state: present

- name: Install software on u2
  hosts: aws_u2
  vars:
    packages:
      - mysql-server
  tasks:
    - name: Update all Ubuntu packages
      become: yes
      apt:
        upgrade: "dist"
      when: ansible_distribution == 'Ubuntu'

    - name: Install mysql on u2
      become: yes
      apt:
        update_cache: yes
        name: "{{ packages }}"
        state: present

    - name: Start mysql service on u2
      become: yes
      service:
        name: mysql
        state: started
        enabled: yes

- name: Install softwares in aws_rhel
  hosts: aws_rhel1
  tasks:
  - name: Install apache packages
    become: yes
    yum:
      name: httpd
      state: present

  - name: ensure httpd is running
    become: yes
    service:
      name: httpd
      state: started
