- name: Wait for the instances to come up and check ssh
  hosts: all
  gather_facts: false
  tasks:
  - name: Wait for SSH to start
    wait_for:
      port: 22
      timeout: 120
    delegate_to: localhost

  - name: Pause for 1 minutes for instance to come up
    pause:
      minutes: 1

- name: Install software on u1
  hosts: aws_u1
  gather_facts: false
  vars:
    packages:
      - openjdk-8-jdk
      - python3
      - mysql-client
      - python3-mysql.connector
      - net-tools
  tasks:
    - name: Update all Ubuntu packages
      become: yes
      apt:
        upgrade: "dist"

    - name: Install all packages
      become: yes
      apt:
        update_cache: yes
        cache_valid_time: 3600
        name: "{{ packages }}"
        state: present



- name: Install software on u2
  hosts: aws_u2
  gather_facts: false
  vars:
    packages:
      - mysql-server
      - python3-pymysql
      - net-tools
  tasks:
    - name: Update all Ubuntu packages
      become: yes
      apt:
        upgrade: "dist"

    - name: Install mysql and other packages on u2
      become: yes
      apt:
        update_cache: yes
        name: "{{ packages }}"
        state: present

    - name: a - Ensure MySQL will listen on all ip interfaces (bind to 0.0.0.0)
      become: yes
      lineinfile:
        dest: /etc/mysql/my.cnf
        regexp: 'bind-address\s*=\s*127\.0\.0\.1\s*'
        line: 'bind-address   = 0.0.0.0'
        state: present
        backrefs: yes

    - name: b - Ensure MySQL will listen on all ip interfaces (bind to 0.0.0.0)
      become: yes
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: 'bind-address\s*=\s*127\.0\.0\.1\s*'
        line: 'bind-address   = 0.0.0.0'
        state: present
        backrefs: yes

    - name: c - Update user id from mysql to root
      become: yes
      lineinfile:
        dest: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: 'user\s*=\s*mysql\s*'
        line: 'user    = root'
        state: present
        backrefs: yes

    - name: Re-Start mysql service on u2
      become: yes
      service:
        name: mysql
        state: restarted
        enabled: yes


- name: Install softwares in aws_rhel
  hosts: aws_rhel1
  tasks:
  - name: Install apache packages
    become: yes
    yum:
      name: httpd
      state: present
  - name: ensure httpd is running
    become: yes
    service:
      name: httpd
      state: started
